server:
    port: 8095
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db?useSSL=false
        username: root
        password: Vi7897527880
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
