server:
    port: 8096
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/login
        username: root
        password: password
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
