server:
  port: 8084

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

kafka:
  ipAddress: localhost:9092
  groupId: group_id11
  outputTopic: indexer
  listeningTopic: location
  containerFactory: userKafkaListenerFactory