server:
  port: 8081
kafka:
  ipAddress: localhost:9092
  groupId: group_id13
  outputTopic: indexer
  linsteningTopic: skills
  containerFactory: userKafkaListenerFactory

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

