server:
  port: 8095

spring:
  application:
    name: QueryService

controller:
  base: /matchmaker/v1
  search: /search


kafka:
  ipAddress: http://localhost:9092
  groupId: group_id69
  outputTopic: query
