kafka:
  ipAddress: localhost:9092
  groupId: akash
  listeningTopic: indexer
  containerFactory: userKafkaListenerFactory

server:
  port: 8010
spring:
  data:
    neo4j:
      uri: bolt://172.23.239.111