kafka:
  ipAddress: localhost:9092
  groupId: akash
  listeningTopic: indexer
  containerFactory: userKafkaListenerFactory

server:
  port: 8001
spring:
  data:
    neo4j:
      uri: bolt://0.0.0.0
      username: neo4j
      password: 123456
