server:
  port: 8008

spring:
  data:
   neo4j:
     uri : bolt://0.0.0.0
     username: neo4j
     password: 123456


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5