server:
  port: 8093

kafka:
  ipAddress: localhost:9092
  groupId: group_id101
  listeningTopic: query
  outputTopic: token
  containerFactory: userKafkaListenerFactory
  success: Successfully saved
  consumed: Consumed
